apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpweb
  namespace: default  # 👈 Add this line
  labels:
    app: tpweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpweb
  strategy: {}
  template:
    metadata:
      labels:
        app: tpweb
    spec:
      containers:
      - name: tejaswi-web-kqjbz
        image: tpathak21/tejaswi_web
        resources: {}
